import type { PersonEntity, PersistentWorldStore, Vec3 } from './worldModel';
import type { ProceduralCityPlan } from './proceduralCity';
import type { ContinuityEngine } from './continuity';

export type EmergencyUnitStatus='available'|'en-route'|'on-scene'|'transporting'|'at-hospital'|'clearing';

export interface EmergencyUnitState {
  id:string;
  label:string;
  position:Vec3;
  status:EmergencyUnitStatus;
  assignedPersonId?:string;
  target:Vec3;
  speedMetresPerSecond:number;
  sceneElapsedSeconds:number;
}

export interface EmergencyResponseSnapshot {
  units:EmergencyUnitState[];
  activeResponses:Array<{personId:string;unitId:string;status:EmergencyUnitStatus;reason:string}>;
}

const clone=<T>(value:T):T=>JSON.parse(JSON.stringify(value)) as T;

export class EmergencyResponseEngine {
  private units=new Map<string,EmergencyUnitState>();
  private reasons=new Map<string,string>();

  constructor(private store:PersistentWorldStore,private city:ProceduralCityPlan,private continuity:ContinuityEngine){
    const base=this.city.buildings.find(building=>building.id==='ems-base')?.position??[135,0,-45] as Vec3;
    this.units.set('ambulance-1',{id:'ambulance-1',label:'Ambulance 1',position:base,status:'available',target:base,speedMetresPerSecond:14,sceneElapsedSeconds:0});
    this.units.set('ambulance-2',{id:'ambulance-2',label:'Ambulance 2',position:[base[0]+8,base[1],base[2]+4],status:'available',target:base,speedMetresPerSecond:13,sceneElapsedSeconds:0});
    this.store.recordEvent('ems.ready',undefined,`units=${this.units.size}; autonomous dispatch follows evidence-gated continuity episodes`);
  }

  snapshot():EmergencyResponseSnapshot {
    const units=[...this.units.values()].map(clone);
    const activeResponses=units.flatMap(unit=>unit.assignedPersonId?[{personId:unit.assignedPersonId,unitId:unit.id,status:unit.status,reason:this.reasons.get(unit.assignedPersonId)??'unspecified simulation trigger'}]:[]);
    return {units,activeResponses};
  }

  dispatchFromContinuity(personId:string,reason:string){
    const episode=this.continuity.episode(personId);if(!episode||episode.stage!=='ambulance')return false;
    if([...this.units.values()].some(unit=>unit.assignedPersonId===personId&&unit.status!=='available'))return true;
    const entity=this.store.entity(personId);if(!entity||entity.kind!=='person')return false;
    const person=entity as PersonEntity;
    const available=[...this.units.values()].filter(unit=>unit.status==='available').sort((a,b)=>distance(a.position,person.position)-distance(b.position,person.position))[0];
    if(!available){this.store.recordEvent('ems.dispatch.unavailable',personId,'no emergency unit currently available; continuity episode preserved');return false;}
    available.assignedPersonId=personId;available.status='en-route';available.target=person.position;available.sceneElapsedSeconds=0;this.reasons.set(personId,reason);
    this.store.recordEvent('ems.dispatched',personId,`${available.id}; reason=${reason}; communication and authority context preserved from world state`);return true;
  }

  step(seconds:number){
    const hospital=this.city.buildings.find(building=>building.id==='hospital-main')?.position??[135,0,-135] as Vec3;
    const base=this.city.buildings.find(building=>building.id==='ems-base')?.position??[135,0,-45] as Vec3;
    for(const unit of this.units.values()){
      if(unit.status==='available')continue;
      const personId=unit.assignedPersonId;
      if(unit.status==='en-route'&&personId){
        const person=this.store.entity(personId);if(person)unit.target=person.position;
        if(this.move(unit,seconds)){unit.status='on-scene';unit.sceneElapsedSeconds=0;this.store.recordEvent('ems.on-scene',personId,`${unit.id}; no treatment inference generated by dispatch engine`);}continue;
      }
      if(unit.status==='on-scene'&&personId){
        unit.sceneElapsedSeconds+=seconds;
        if(unit.sceneElapsedSeconds>=20){unit.status='transporting';unit.target=hospital;this.store.recordEvent('ems.transport.started',personId,`${unit.id}->hospital-main; continuity context retained`);}continue;
      }
      if(unit.status==='transporting'&&personId){
        unit.target=hospital;
        if(this.move(unit,seconds)){unit.status='at-hospital';this.continuity.advance(personId,'ed','autonomous emergency transport arrived at ED');this.store.recordEvent('ems.hospital-arrival',personId,`${unit.id}; handover to ED continuity stage`);}continue;
      }
      if(unit.status==='at-hospital'){unit.sceneElapsedSeconds+=seconds;if(unit.sceneElapsedSeconds>=35){unit.status='clearing';unit.target=base;unit.sceneElapsedSeconds=0;}continue;}
      if(unit.status==='clearing'){
        if(this.move(unit,seconds)){if(personId)this.reasons.delete(personId);unit.status='available';delete unit.assignedPersonId;unit.target=base;this.store.recordEvent('ems.unit.available',undefined,`${unit.id} returned to service`);}
      }
    }
  }

  private move(unit:EmergencyUnitState,seconds:number){
    const [x,y,z]=unit.position,[tx,,tz]=unit.target,dx=tx-x,dz=tz-z,d=Math.hypot(dx,dz);
    if(d<1){unit.position=unit.target;return true;}
    const amount=Math.min(d,unit.speedMetresPerSecond*seconds);unit.position=[x+dx/d*amount,y,z+dz/d*amount];return amount>=d-.001;
  }
}

const distance=(a:Vec3,b:Vec3)=>Math.hypot(a[0]-b[0],a[2]-b[2]);
