import type{PersonEntity,PersistentWorldStore,Vec3}from'./worldModel';import type{CityBuilding,ProceduralCityPlan}from'./proceduralCity';
export interface HomeState{id:string;residentIds:string[];entryOperational:boolean;mainsPower:boolean;backupPower:boolean;chargingAvailable:boolean;quietSpace:boolean;}
export interface TransportVehicleState{id:string;label:string;position:Vec3;capacity:number;wheelchairSpaces:number;passengers:string[];reservedWheelchairSpaces:string[];route:string[];currentStopIndex:number;nextStopIndex:number;dwellSeconds:number;status:'dwelling'|'moving'|'out-of-service';speedMetresPerSecond:number;}
export interface TransportTripRequest{id:string;personId:string;originId:string;destinationId:string;status:'requested'|'allocated'|'boarded'|'completed'|'unavailable';vehicleId?:string;reason:string;supportRequested:boolean;}
export interface HomeTransportSnapshot{homes:HomeState[];vehicles:TransportVehicleState[];trips:TransportTripRequest[];}
const clone=<T>(v:T):T=>JSON.parse(JSON.stringify(v))as T;function buildingPosition(plan:ProceduralCityPlan,id:string):Vec3|undefined{return plan.buildings.find(b=>b.id===id)?.position;}
export class HomeTransportEngine{private homes=new Map<string,HomeState>();private vehicles=new Map<string,TransportVehicleState>();private trips=new Map<string,TransportTripRequest>();private requestCounter=0;
 constructor(private store:PersistentWorldStore,private plan:ProceduralCityPlan){for(const b of plan.buildings.filter(i=>i.kind==='home'))this.homes.set(b.id,this.homeFromBuilding(b));const route=['home-maya','community-hub','city-transport-hub','hospital-main','employment-centre','home-maya'];this.vehicles.set('city-access-shuttle',{id:'city-access-shuttle',label:'City accessible shuttle',position:buildingPosition(plan,'city-transport-hub')??[-180,0,-180],capacity:8,wheelchairSpaces:3,passengers:[],reservedWheelchairSpaces:[],route,currentStopIndex:2,nextStopIndex:3,dwellSeconds:12,status:'dwelling',speedMetresPerSecond:9});this.store.recordEvent('services.home-transport.ready',undefined,`homes=${this.homes.size}; vehicles=${this.vehicles.size}`);}
 snapshot():HomeTransportSnapshot{return{homes:[...this.homes.values()].map(clone),vehicles:[...this.vehicles.values()].map(clone),trips:[...this.trips.values()].map(clone)};}homeForPerson(personId:string){return[...this.homes.values()].find(h=>h.residentIds.includes(personId));}
 setHomePower(homeId:string,mainsPower:boolean){const h=this.homes.get(homeId);if(!h)return false;h.mainsPower=mainsPower;this.store.recordEvent('home.power.changed',homeId,`mains=${mainsPower}; backup=${h.backupPower}; charging=${h.chargingAvailable}`);return true;}
 requestTrip(personId:string,originId:string,destinationId:string):TransportTripRequest|undefined{const e=this.store.entity(personId);if(!e||e.kind!=='person')return undefined;const p=e as PersonEntity,v=[...this.vehicles.values()].find(i=>i.status!=='out-of-service'),id=`trip-${++this.requestCounter}`;if(!v){const t:TransportTripRequest={id,personId,originId,destinationId,status:'unavailable',reason:'no represented transport vehicle available; preserve travel goal',supportRequested:false};this.trips.set(id,t);return clone(t);}const wc=p.mobility.mode==='powered-wheelchair'||p.mobility.mode==='manual-wheelchair',wcAvailable=v.reservedWheelchairSpaces.length<v.wheelchairSpaces,capacity=v.passengers.length<v.capacity;if(!capacity||(wc&&!wcAvailable)){const t:TransportTripRequest={id,personId,originId,destinationId,status:'unavailable',reason:wc?'wheelchair space unavailable on current service':'vehicle capacity unavailable',supportRequested:false};this.trips.set(id,t);return clone(t);}const t:TransportTripRequest={id,personId,originId,destinationId,status:'allocated',vehicleId:v.id,reason:'accessible capacity allocated; boarding remains an explicit in-place action',supportRequested:false};this.trips.set(id,t);if(wc)v.reservedWheelchairSpaces.push(personId);this.store.recordEvent('transport.trip.allocated',personId,`${originId}->${destinationId}; vehicle=${v.id}; support not assumed`);return clone(t);}
 requestSupport(tripId:string){const t=this.trips.get(tripId);if(!t)return false;t.supportRequested=true;this.store.recordEvent('transport.support.requested',t.personId,`trip=${tripId}; explicit request`);return true;}
 board(tripId:string){const t=this.trips.get(tripId);if(!t||t.status!=='allocated'||!t.vehicleId)return false;const v=this.vehicles.get(t.vehicleId);if(!v||v.status!=='dwelling')return false;const currentStop=v.route[v.currentStopIndex];if(currentStop!==t.originId)return false;const p=this.store.entity(t.personId);const stop=this.stopPosition(currentStop);if(!p||!stop||Math.hypot(p.position[0]-stop[0],p.position[2]-stop[2])>6){this.store.recordEvent('transport.boarding.wait',t.personId,`trip=${tripId}; person is not at boarding stop; intent preserved`);return false;}if(!v.passengers.includes(t.personId))v.passengers.push(t.personId);t.status='boarded';this.store.recordEvent('transport.boarded',t.personId,`vehicle=${v.id}; destination=${t.destinationId}; explicit boarding action`);return true;}
 step(seconds:number){for(const v of this.vehicles.values()){if(v.status==='out-of-service')continue;if(v.status==='dwelling'){v.dwellSeconds-=seconds;if(v.dwellSeconds<=0){v.status='moving';v.nextStopIndex=(v.currentStopIndex+1)%v.route.length;}continue;}const targetId=v.route[v.nextStopIndex];if(!targetId)continue;const target=this.stopPosition(targetId);if(!target)continue;const[x,y,z]=v.position,dx=target[0]-x,dz=target[2]-z,d=Math.hypot(dx,dz);if(d<1){v.position=target;v.currentStopIndex=v.nextStopIndex;v.status='dwelling';v.dwellSeconds=12;this.completeTripsAtStop(v,targetId);continue;}const amount=Math.min(d,v.speedMetresPerSecond*seconds);v.position=[x+dx/d*amount,y,z+dz/d*amount];}}
 private stopPosition(id:string):Vec3|undefined{return this.store.entity(id)?.position??buildingPosition(this.plan,id);}private completeTripsAtStop(v:TransportVehicleState,stopId:string){for(const t of this.trips.values())if(t.vehicleId===v.id&&t.status==='boarded'&&t.destinationId===stopId){t.status='completed';v.passengers=v.passengers.filter(id=>id!==t.personId);v.reservedWheelchairSpaces=v.reservedWheelchairSpaces.filter(id=>id!==t.personId);this.store.recordEvent('transport.trip.completed',t.personId,`arrived=${stopId}`);}}private homeFromBuilding(b:CityBuilding):HomeState{return{id:b.id,residentIds:[...b.residentIds],entryOperational:true,mainsPower:true,backupPower:b.access.charging,chargingAvailable:b.access.charging,quietSpace:b.access.quietSpace};}}
