import React,{useEffect,useRef,useState}from'react';
import{InfrastructureEntity,PersonEntity,PersistentWorldStore,accessAssessment}from'./worldModel';
import{WorldRuntime}from'./liveWorldLoop';
import{nearbyEntities,createSpatialIntent,evaluateSpatialIntent}from'./spatialInteraction';
import{WOLFRAM_ROUTE_MODEL}from'./accessibleNavigation';
import{WOLFRAM_OBJECT_MODELS}from'./objectInteractions';
import{WOLFRAM_SOCIAL_MODEL}from'./socialEncounters';
import{WOLFRAM_CONTINUITY_MODEL}from'./continuity';
import{createCityVisuals,type CityVisualController}from'./cityRendering';

export function OpenWorldWeb(){
 const canvasRef=useRef<HTMLCanvasElement|null>(null),storeRef=useRef<PersistentWorldStore|null>(null),runtimeRef=useRef<WorldRuntime|null>(null),tripRef=useRef<string|null>(null);if(!storeRef.current)storeRef.current=new PersistentWorldStore();
 const[status,setStatus]=useState('Loading world…'),[xr,setXr]=useState('Checking WebXR…'),[access,setAccess]=useState('ACCESS NETWORK ONLINE'),[life,setLife]=useState('DAILY LIFE ENGINE STARTING'),[clinical,setClinical]=useState('CLINICAL BRIDGE · STANDBY'),[nearby,setNearby]=useState('NEARBY · scanning'),[route,setRoute]=useState('NAVMESH · calculating'),[objects,setObjects]=useState('OBJECT ENGINE · online'),[encounters,setEncounters]=useState('SOCIAL ENCOUNTERS · scanning'),[continuity,setContinuity]=useState('CONTINUITY · community'),[city,setCity]=useState('CITY · generating'),[services,setServices]=useState('HOMES + TRANSPORT · starting'),[ems,setEms]=useState('EMS · available'),[navVisible,setNavVisible]=useState(false);
 useEffect(()=>{let disposed=false,engine:any,scene:any,routeMesh:any,cityVisuals:CityVisualController|undefined;const store=storeRef.current!,runtime=new WorldRuntime(store);runtimeRef.current=runtime;
  const boot=async()=>{const B=await import('@babylonjs/core');await import('@babylonjs/loaders');if(!canvasRef.current||disposed)return;engine=new B.Engine(canvasRef.current,true,{preserveDrawingBuffer:true,stencil:true});scene=new B.Scene(engine);scene.clearColor=new B.Color4(.72,.86,.96,1);scene.collisionsEnabled=true;
   const camera=new B.UniversalCamera('player',new B.Vector3(0,1.65,-16),scene);camera.attachControl(canvasRef.current,true);camera.speed=.55;camera.angularSensibility=3500;camera.applyGravity=true;camera.checkCollisions=true;camera.ellipsoid=new B.Vector3(.5,.9,.5);camera.keysUp.push(87);camera.keysDown.push(83);camera.keysLeft.push(65);camera.keysRight.push(68);
   new B.HemisphericLight('sky',new B.Vector3(0,1,0),scene).intensity=.85;new B.DirectionalLight('sun',new B.Vector3(-.4,-1,.25),scene).intensity=.7;
   const material=(n:string,r:number,g:number,b:number)=>{const m=new B.StandardMaterial(n,scene);m.diffuseColor=new B.Color3(r,g,b);return m;};
   const ground=B.MeshBuilder.CreateGround('city-ground',{width:560,height:560},scene);ground.checkCollisions=true;ground.material=material('ground',.38,.55,.35);const path=B.MeshBuilder.CreateGround('central-accessible-path',{width:12,height:190},scene);path.position.y=.015;path.material=material('path',.62,.61,.57);
   const buildingMat=material('building',.72,.76,.78),glass=material('glass',.25,.55,.7);glass.alpha=.72;const doorMeshes=new Map<string,{mesh:any,closedX:number}>();
   const makeBuilding=(id:string,label:string,x:number,z:number,w:number,d:number,h:number)=>{const body=B.MeshBuilder.CreateBox(label,{width:w,depth:d,height:h},scene);body.position.set(x,h/2,z);body.material=buildingMat;body.checkCollisions=true;const door=B.MeshBuilder.CreateBox(id,{width:3.2,depth:.12,height:2.7},scene);door.position.set(x,1.35,z-d/2-.07);door.material=glass;doorMeshes.set(id,{mesh:door,closedX:x});};
   makeBuilding('clinical-door','Clinical Simulation Centre',-24,8,28,20,10);makeBuilding('community-door','Community Hub',25,22,26,18,7);makeBuilding('rehab-door','Rehabilitation Lab',24,-28,24,18,8);makeBuilding('transit-door','Accessible Transit Station',-25,-34,30,15,6);
   cityVisuals=createCityVisuals(B,scene,runtime,material);
   const personMat=material('people',.22,.32,.55),accessMat=material('access',.16,.48,.5),unavailableMat=material('unavailable',.48,.2,.2),meshes=new Map<string,any>();
   const createEntityMesh=(entity:any)=>{if(meshes.has(entity.id))return;if(entity.kind==='person'){const p=entity as PersonEntity,body=B.MeshBuilder.CreateCapsule(entity.id,{height:1.35,radius:.3},scene);body.position.set(p.position[0],1.05,p.position[2]);body.material=personMat;meshes.set(entity.id,body);if(p.mobility.mode.includes('wheelchair')){const chair=B.MeshBuilder.CreateBox(entity.id+'-mobility',{width:.85,height:.55,depth:1.05},scene);chair.position.set(p.position[0],.38,p.position[2]);chair.material=personMat;meshes.set(entity.id+'-mobility',chair);}}else if(entity.kind==='infrastructure'&&entity.tags.includes('access')){const i=entity as InfrastructureEntity,marker=B.MeshBuilder.CreateCylinder(entity.id,{height:1.5,diameter:.65},scene);marker.position.set(i.position[0],.75,i.position[2]);marker.material=i.operational?accessMat:unavailableMat;meshes.set(i.id,marker);}};
   for(const entity of store.snapshot().entities)createEntityMesh(entity);const liftCabin=B.MeshBuilder.CreateBox('station-lift-cabin',{width:2.4,height:2.6,depth:2.4},scene);liftCabin.position.set(-20,1.3,-34);liftCabin.material=glass;const charger=B.MeshBuilder.CreateCylinder('aac-charge-visual',{height:1.2,diameter:1.2},scene);charger.position.set(20,.6,20);charger.material=accessMat;const shuttle=B.MeshBuilder.CreateBox('community-shuttle',{width:3,height:2.8,depth:7},scene);shuttle.position.set(-30,1.4,-39);shuttle.material=buildingMat;
   for(let i=0;i<36;i++){const a=i*2.399,r=238-(i%4)*9,t=B.MeshBuilder.CreateCylinder('tree-'+i,{height:5,diameterTop:.5,diameterBottom:2.4,tessellation:7},scene);t.position.set(Math.cos(a)*r,2.5,Math.sin(a)*r);t.material=material('tree-'+i,.16,.38,.17);}
   let last=performance.now(),uiLast=0,lastRouteKey='';scene.onBeforeRenderObservable.add(()=>{const now=performance.now(),elapsed=Math.max(0,(now-last)/1000);last=now;const frame=runtime.step(elapsed),snapshot=store.snapshot();cityVisuals?.update(frame);
    for(const entity of snapshot.entities){createEntityMesh(entity);const mesh=meshes.get(entity.id);if(mesh){mesh.position.x=entity.position[0];mesh.position.z=entity.position[2];if(entity.kind==='infrastructure')mesh.material=(entity as InfrastructureEntity).operational?accessMat:unavailableMat;}const mobility=meshes.get(entity.id+'-mobility');if(mobility){mobility.position.x=entity.position[0];mobility.position.z=entity.position[2];}}
    for(const door of frame.objects.doors){const record=doorMeshes.get(door.id);if(record)record.mesh.position.x=record.closedX+door.progress*2.7;}liftCabin.position.y=1.3+frame.objects.lift.positionMetres;const mayaCharge=frame.objects.chargers.find(session=>session.personId==='maya');if(mayaCharge)charger.scaling.y=.5+mayaCharge.currentPercent/100;shuttle.position.y=frame.objects.transport.passengers.includes('maya')?1.55:1.4;
    const mayaRoute=frame.navMeshRoutes.maya,routeKey=mayaRoute?.triangleIds.join('>')??'';if(routeKey!==lastRouteKey){lastRouteKey=routeKey;routeMesh?.dispose?.();if(mayaRoute&&mayaRoute.points.length>1)routeMesh=B.MeshBuilder.CreateLines('maya-city-navmesh-route',{points:mayaRoute.points.map(p=>new B.Vector3(p[0],.12,p[2]))},scene);}
    if(now-uiLast>1000){uiLast=now;const maya=store.entity('maya') as PersonEntity|undefined,lift=store.entity('station-lift') as InfrastructureEntity|undefined;if(maya&&lift){const a=accessAssessment(maya,lift);setAccess(`TRANSIT ACCESS: ${a.pass?'AVAILABLE':'BARRIER'} · ${a.cause}`);const close=nearbyEntities(snapshot,'maya',8);setNearby(`NEARBY MAYA · ${close.length?close.map(x=>x.entity.label).join(' · '):'none within 8m'}`);}const activity=frame.activities.find(x=>x.personId==='maya');setLife(activity?`MAYA · ${activity.kind.toUpperCase()} · ${activity.rationale}`:'MAYA · NO ACTIVE PLAN');const bridge=frame.clinical.find(x=>x.personId==='maya');setClinical(`CLINICAL BRIDGE · ${(bridge?.status??'continue-world').toUpperCase().replace(/-/g,' ')}`);setRoute(mayaRoute?`CITY NAVMESH · ${mayaRoute.triangleIds.length} triangles · cost ${mayaRoute.cost.toFixed(1)} · ${mayaRoute.points.length} waypoints`:'CITY NAVMESH · no viable route represented');const doorSummary=frame.objects.doors.map(d=>`${d.id}:${d.phase}`).join(' · ');setObjects(`OBJECTS · ${doorSummary} · lift ${frame.objects.lift.phase}@${frame.objects.lift.positionMetres.toFixed(1)}m`);setEncounters(frame.encounters.length?`ENCOUNTERS · ${frame.encounters.map(e=>`${e.a}↔${e.b} ${e.status} ${e.score.toFixed(2)}${e.supportRequested?' support-requested':''}`).join(' · ')}`:'ENCOUNTERS · none above threshold');setContinuity(`CONTINUITY · ${frame.continuity.maya??'community'}`);setCity(`CITY · seed ${runtime.cityPlan().seed} · ${runtime.cityPlan().districts.length} districts · ${runtime.cityPlan().buildings.length} buildings · navmesh ${runtime.navMesh().triangles.length} triangles`);const v=frame.services.vehicles[0],home=frame.services.homes.find(h=>h.residentIds.includes('maya')),trip=frame.services.trips.find(t=>t.id===tripRef.current);setServices(`HOME + TRANSPORT · Maya home power ${home?.mainsPower?'ON':'OFF'} · shuttle ${v?.status??'unknown'} · trip ${trip?.status??'none'}`);const response=frame.emergency.activeResponses.find(r=>r.personId==='maya'),unit=response?frame.emergency.units.find(u=>u.id===response.unitId):undefined;setEms(response?`EMS · ${response.unitId} ${response.status} · position ${unit?.position[0].toFixed(0)},${unit?.position[2].toFixed(0)}`:'EMS · units available · no active Maya response');}}
   });
   try{const helper=await scene.createDefaultXRExperienceAsync({floorMeshes:[ground,path],disableTeleportation:false});setXr(helper.baseExperience?'VR READY · controller, gaze and teleport supported':'VR unavailable');}catch{setXr('WebXR not available on this browser/device');}setStatus('PROCEDURAL DISABILITY CITY ONLINE');engine.runRenderLoop(()=>scene.render());const resize=()=>engine.resize();window.addEventListener('resize',resize);(scene as any).__cleanup=()=>window.removeEventListener('resize',resize);
  };boot();return()=>{disposed=true;scene?.__cleanup?.();routeMesh?.dispose?.();cityVisuals?.dispose();scene?.dispose?.();engine?.dispose?.();};},[]);
 const runtime=()=>runtimeRef.current!;const toggleLift=()=>{const s=storeRef.current!,lift=s.entity('station-lift') as InfrastructureEntity;s.setInfrastructure('station-lift',!lift.operational);};const toggleAAC=()=>{const s=storeRef.current!,maya=s.entity('maya') as PersonEntity;s.setCommunicationAccess('maya',maya.communication.access==='available'?'degraded':'available');};
 const interactNearest=()=>{const s=storeRef.current!,state=s.snapshot(),target=nearbyEntities(state,'maya',8)[0];if(!target){setStatus('INTERACTION · no nearby target');return;}const intent=createSpatialIntent('maya',target.entity.id,target.entity.kind==='person'?'communicate':'use','touch'),result=evaluateSpatialIntent(state,intent);s.recordEvent('world.intent','maya',`${intent.action} ${target.entity.label}: ${result.reason}`);setStatus(`INTERACTION · ${target.entity.label} · ${result.allowed?'AVAILABLE':'BLOCKED'} · ${result.reason}`);};
 const openDoor=()=>runtime().objectEngine().requestDoor('community-door','maya');const moveLift=()=>{const lift=runtime().objectEngine().snapshot().lift;runtime().objectEngine().requestLift(lift.currentLevel===0?1:0,'maya');};const chargeAAC=()=>runtime().objectEngine().startCharging('maya',30);const boardTransport=()=>{const result=runtime().objectEngine().boardTransport('maya');setStatus(`LOCAL TRANSPORT · ${result.reason}`);};const requestSupport=()=>{runtime().requestSupport('maya','liam');setStatus('SUPPORT · Maya explicitly requested support from Liam');};
 const requestCityTrip=()=>{const trip=runtime().requestCityTrip('maya','community-hub','hospital-main');tripRef.current=trip?.id??null;setStatus(`CITY TRIP · ${trip?.status??'not created'} · ${trip?.reason??'person unavailable'}`);};const boardCityTrip=()=>{const id=tripRef.current;if(!id){setStatus('CITY TRIP · request a trip first');return;}setStatus(runtime().boardCityTrip(id)?'CITY TRIP · boarded by explicit action':'CITY TRIP · boarding unavailable at current stop/location');};
 const beginContinuity=()=>{runtime().beginContinuity('maya');setStatus('CONTINUITY + EMS · educational community deterioration episode started');};const advanceContinuity=()=>{runtime().advanceContinuity('maya');setStatus(`CONTINUITY · ${runtime().continuity().summary('maya')}`);};const toggleNavmesh=()=>{const visible=(runtimeRef.current&&(window as any).__mertCityVisuals)?false:undefined;void visible;setStatus('NAVMESH · use visual toggle');setNavVisible(value=>!value);document.dispatchEvent(new CustomEvent('mert-toggle-navmesh'));};const resetWorld=()=>{storeRef.current!.reset();setStatus('WORLD RESET · reload to reseed city and population');};
 // Bridge the DOM control to the Babylon-owned visual controller without making DOM the scene owner.
 useEffect(()=>{const handler=()=>{const event=new CustomEvent('mert-navmesh-request');document.dispatchEvent(event);};void handler;},[]);
 return <div style={{position:'fixed',inset:0,background:'#111'}}><canvas ref={canvasRef} aria-label="Interactive persistent disability-inclusive procedural city. Accessible navmesh routes, homes, transport services, emergency response and world-to-clinical continuity are rendered in Babylon.js and available in WebXR." style={{width:'100%',height:'100%',touchAction:'none',display:'block'}}/><div role="status" aria-live="polite" style={{position:'absolute',top:16,left:16,maxWidth:800,maxHeight:'74vh',overflow:'auto',padding:'12px 14px',borderRadius:12,background:'rgba(8,18,28,.93)',color:'white',fontFamily:'system-ui'}}><strong>MERT · PROCEDURAL DISABILITY CITY · STEPS 25–28</strong><br/><span>{status}</span><br/><span>{xr}</span><br/><span>{city}</span><br/><span>{access}</span><br/><span>{life}</span><br/><span>{route}</span><br/><span>{services}</span><br/><span>{ems}</span><br/><span>{objects}</span><br/><span>{nearby}</span><br/><span>{encounters}</span><br/><span>{clinical}</span><br/><span>{continuity}</span><div style={{display:'flex',gap:8,marginTop:10,flexWrap:'wrap'}}><button onClick={interactNearest} style={{padding:10}}>Interact with nearest</button><button onClick={requestCityTrip} style={{padding:10}}>Request accessible city trip</button><button onClick={boardCityTrip} style={{padding:10}}>Board allocated city trip</button><button onClick={beginContinuity} style={{padding:10}}>Start continuity + EMS</button><button onClick={advanceContinuity} style={{padding:10}}>Advance care journey</button><button onClick={openDoor} style={{padding:10}}>Open Community door</button><button onClick={moveLift} style={{padding:10}}>Move station lift</button><button onClick={chargeAAC} style={{padding:10}}>Charge Maya AAC</button><button onClick={boardTransport} style={{padding:10}}>Board local shuttle</button><button onClick={requestSupport} style={{padding:10}}>Request Liam support</button><button onClick={toggleLift} style={{padding:10}}>Toggle lift availability</button><button onClick={toggleAAC} style={{padding:10}}>Toggle Maya AAC</button><button onClick={toggleNavmesh} style={{padding:10}}>Navmesh overlay: {navVisible?'ON':'OFF'}</button><button onClick={resetWorld} style={{padding:10}}>Reset world</button></div></div><div style={{position:'absolute',right:16,bottom:16,maxWidth:490,padding:12,borderRadius:12,background:'rgba(8,18,28,.88)',color:'white',fontFamily:'system-ui',fontSize:13}}><strong>Simulation computation layer</strong><br/>Route weighting retains {WOLFRAM_ROUTE_MODEL.formula}. Lift: {WOLFRAM_OBJECT_MODELS.liftSmoothstep}. Charger: {WOLFRAM_OBJECT_MODELS.charger}. Social: {WOLFRAM_SOCIAL_MODEL.formula}. Continuity graph remains acyclic with {WOLFRAM_CONTINUITY_MODEL.unexpectedDeadEnds} unexpected dead ends. Procedural-city gradients, speeds and timings are simulation parameters, not statutory accessibility standards or clinical treatment guidance.</div></div>;
}
